server:
  port: 8081

spring:
  application:
    name: job-agent

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/jobagent
      database: jobagent

  # Spring AI - OpenAI (used for AI filtering)
  ai:
    google:
      genai:
        api-key: api_key
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.2
    retry:
      max-attempts: 1       # no retries
      on-client-errors: false

# Job Agent Configuration
job-agent:
  # Your profile — edit these to match your skills
  candidate:
    skills:
      - Java
    experience-years: 4.5
    preferred-roles:
      - Software Development Engineer
    preferred-locations:
      - Delhi
    min-salary: 2000000
    limits:
      max-jobs-per-run: 5        # max jobs to analyze per agent run
      delay-between-calls-ms: 5000  # 2 second delay between Gemini calls# in INR per annum

  # Scheduler: runs at 8 AM and 8 PM daily
  scheduler:
    cron-morning: "0 0 8 * * *"
    cron-evening: "0 0 20 * * *"

  # Job portals to scrape
  portals:
    linkedin:
      enabled: true
      base-url: https://www.linkedin.com/jobs/search
    remotive:
      enabled: false
      base-url: https://remotive.com/api/remote-jobs
    remoteok:
      enabled: false
      base-url: https://remoteok.com/api
    arbeitnow:
      enabled: false
      base-url: https://www.arbeitnow.com/api/job-board-api

logging:
  level:
    com.jobagent: DEBUG
    org.springframework.ai: INFO
